version: '3.8'

services:
    postgres:
        container_name: postgresql-crud-graphql
        image: 'postgres:latest'
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432